name: Update

on:
  push:
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v2
    - name: Step 2 - Build
      run: |
        wget https://raw.githubusercontent.com/hezhijie0327/GFWList2AGH/main/gfwlist2adguardhome/blacklist_lite_split.txt -O ./AdGuardHome.list
        wget https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad.txt -O ./Halflife.list
        wget https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt -O ./Spam404.list
        wget https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt -O ./BarbBlock.list
        wget https://raw.githubusercontent.com/neodevpro/neodevhost/master/lite_adblocker -O ./Neo-Dev-Host.list
        wget https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt -O ./Scam-Blocklist-by-DurableNapkin.list
        wget https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list -O ./The-Big-List-of-Hacked-Malware-Web-Sites.list
    - name: Step 3 - Release
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update